server:
  port: ${server_port:1999}
spring:
  profiles:
    active: test
  application:
    name: gift-shop
  # Email Temporarily disab;ed
  # ENble it at OrderMainServiceImpl.java line 168
  mail:
    host: smtp.sendgrid.net
    port: 25
    ssl: no
    tls: yes
    username: apikey
    password: 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
    protocol: smtp

# JTW Config
jwt:
  secret: ${jwt_secret:thisisathirtycharacterlongstring}
  expiration: 3600000

google:
  CLIENT_ID: 120787335948-g4r6bof29ub3vaaaiu7pc01jd5dalooq.apps.googleusercontent.com

facebook:
  TOKEN_VALIDATION_URL: https://graph.facebook.com/me?access_token=

stripe:
  key: ${stripe_key:sk_test_51I3zWOI8py6Rj5ufAOC0uwcqJy64pIGVg5OK9O80NqICeXosLJYYlDKESNeD0NRTudoL6MtF6u7n6e9tjseDGnZW00JkeuTLoT}

razor:
  publicKey: rzp_test_QHK5P7ne66SdWo
  privateKey: XeaLw0YDUXDck0tfb4WzqEaX
